server:
  port: 8080

jwt:
  signerKey: adaksdkasmfomio43o5343mogmsdimsdngknsdkfanklngsngdlklskdn

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity
    username: root
    password: manh123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true